worker_processes auto;
error_log stderr info;
pid /tmp/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/nginx/client-body;
    proxy_temp_path /tmp/nginx/proxy;
    resolver 127.0.0.11 ipv6=off valid=5s;
    client_max_body_size 25G;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 30888;

        location = /health {
            return 200 'ok';
            add_header Content-Type text/plain;
        }

        location /vst/api/v1/sensor/ {
            rewrite ^/vst/api/v1/sensor/(.*) /api/v1/sensor/$1 break;
            set $sensor_backend http://vios-sensor-singleton:30000;
            proxy_pass $sensor_backend;
            proxy_http_version 1.1;
        }

        location /vst/api/v1/ {
            rewrite ^/vst/api/v1/(.*) /api/v1/$1 break;
            set $stream_backend http://vios-streamprocessor:30001;
            proxy_pass $stream_backend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_buffering off;
            proxy_request_buffering off;
        }

        location /vst/storage/ {
            rewrite ^/vst/storage/(.*) /storage/$1 break;
            set $stream_backend http://vios-streamprocessor:30001;
            proxy_pass $stream_backend;
            proxy_http_version 1.1;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}
